SRCS = apg.c
HDRS = Aalgo.h   Ahash.h     Alognode.h  Aop.h       Aphynode.h  Asearch.h
OBJS = apg.o
CLEANABLES = $(OBJS) 

default : apg.o

include ../Config.make
include ../Makefile.common

include ./$(MAKE_DEPEND_FILE)
